//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anno1800ModLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anno1800ModLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string AboutButtonText {
            get {
                return ResourceManager.GetString("AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anno Union ähnelt.
        /// </summary>
        public static string AnnoUnionText {
            get {
                return ResourceManager.GetString("AnnoUnionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string HomeButtonText {
            get {
                return ResourceManager.GetString("HomeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Path:  ähnelt.
        /// </summary>
        public static string HomeViewGamePathText {
            get {
                return ResourceManager.GetString("HomeViewGamePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a Repository from Github ähnelt.
        /// </summary>
        public static string HomeViewHintAssistGithub {
            get {
                return ResourceManager.GetString("HomeViewHintAssistGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path of the profile file you want to install. ähnelt.
        /// </summary>
        public static string HomeViewHintAssistLocalFile {
            get {
                return ResourceManager.GetString("HomeViewHintAssistLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the URL of the mod you wish to install ähnelt.
        /// </summary>
        public static string HomeViewHintAssistNexus {
            get {
                return ResourceManager.GetString("HomeViewHintAssistNexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string HomeViewImportButtonText {
            get {
                return ResourceManager.GetString("HomeViewImportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install from Github ähnelt.
        /// </summary>
        public static string HomeViewInstallFromGithubText {
            get {
                return ResourceManager.GetString("HomeViewInstallFromGithubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install from Nexusmods ähnelt.
        /// </summary>
        public static string HomeViewInstallFromNexusText {
            get {
                return ResourceManager.GetString("HomeViewInstallFromNexusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install from ZIP ähnelt.
        /// </summary>
        public static string HomeViewInstallFromZipText {
            get {
                return ResourceManager.GetString("HomeViewInstallFromZipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install Modloader ähnelt.
        /// </summary>
        public static string HomeViewInstallModloaderText {
            get {
                return ResourceManager.GetString("HomeViewInstallModloaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modding Setup ähnelt.
        /// </summary>
        public static string HomeViewModdingSetupText {
            get {
                return ResourceManager.GetString("HomeViewModdingSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Mod Folder ähnelt.
        /// </summary>
        public static string HomeViewModfolderCreateText {
            get {
                return ResourceManager.GetString("HomeViewModfolderCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod Folder Path ähnelt.
        /// </summary>
        public static string HomeViewModfolderPathText {
            get {
                return ResourceManager.GetString("HomeViewModfolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4ʞʞz0ɔʞ7 repo ähnelt.
        /// </summary>
        public static string HomeViewRepoComboBoxAkkRepoText {
            get {
                return ResourceManager.GetString("HomeViewRepoComboBoxAkkRepoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spice it Up repo ähnelt.
        /// </summary>
        public static string HomeViewRepoComboBoxSIURepoText {
            get {
                return ResourceManager.GetString("HomeViewRepoComboBoxSIURepoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search and select from local drives. ähnelt.
        /// </summary>
        public static string HomeViewSearchTooltipText {
            get {
                return ResourceManager.GetString("HomeViewSearchTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Game Path ähnelt.
        /// </summary>
        public static string HomeViewSetGamePathText {
            get {
                return ResourceManager.GetString("HomeViewSetGamePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search and select from local drives ähnelt.
        /// </summary>
        public static string HomeViewTooltipInstallFromLocal {
            get {
                return ResourceManager.GetString("HomeViewTooltipInstallFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install using the built-in mod browser. ähnelt.
        /// </summary>
        public static string HomeViewTooltipInstallText {
            get {
                return ResourceManager.GetString("HomeViewTooltipInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mods ähnelt.
        /// </summary>
        public static string ModsButtonText {
            get {
                return ResourceManager.GetString("ModsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mod List ähnelt.
        /// </summary>
        public static string ModViewModListText {
            get {
                return ResourceManager.GetString("ModViewModListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string NewsButtonText {
            get {
                return ResourceManager.GetString("NewsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
    }
}
